//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_VreeInput : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean NoButton
        {
            get
            {
                return SteamVR_Actions.vreeInput_NoButton;
            }
        }
        
        public virtual SteamVR_Action_Vector2 Thumbpad
        {
            get
            {
                return SteamVR_Actions.vreeInput_Thumbpad;
            }
        }
        
        public virtual SteamVR_Action_Single IndexTrigger
        {
            get
            {
                return SteamVR_Actions.vreeInput_IndexTrigger;
            }
        }
        
        public virtual SteamVR_Action_Single HandTrigger
        {
            get
            {
                return SteamVR_Actions.vreeInput_HandTrigger;
            }
        }
        
        public virtual SteamVR_Action_Boolean Menu
        {
            get
            {
                return SteamVR_Actions.vreeInput_Menu;
            }
        }
        
        public virtual SteamVR_Action_Boolean IndexTriggerPress
        {
            get
            {
                return SteamVR_Actions.vreeInput_IndexTriggerPress;
            }
        }
        
        public virtual SteamVR_Action_Boolean HandTriggerPress
        {
            get
            {
                return SteamVR_Actions.vreeInput_HandTriggerPress;
            }
        }
        
        public virtual SteamVR_Action_Boolean ThumbpadClick
        {
            get
            {
                return SteamVR_Actions.vreeInput_ThumbpadClick;
            }
        }
    }
}
